# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SudokuSolver.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import sys

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SudokuSolver(object):
    def setupUi(self, SudokuSolver):
        SudokuSolver.setObjectName(_fromUtf8("SudokuSolver"))
        SudokuSolver.resize(802, 594)
        self.centralwidget = QtGui.QWidget(SudokuSolver)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.toolBox = QtGui.QToolBox(self.centralwidget)
        self.toolBox.setGeometry(QtCore.QRect(20, 20, 761, 371))
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 761, 307))
        self.page.setObjectName(_fromUtf8("page"))
        self.gridLayoutWidget = QtGui.QWidget(self.page)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 23, 761, 241))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(20, -1, 20, -1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.radioButton_6 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_6.setChecked(True)
        self.radioButton_6.setObjectName(_fromUtf8("radioButton_6"))
        self.gridLayout_2.addWidget(self.radioButton_6, 0, 4, 1, 1)
        self.radioButton_5 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_5.setObjectName(_fromUtf8("radioButton_5"))
        self.gridLayout_2.addWidget(self.radioButton_5, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 5, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 7, 2, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.radioButton = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton.setChecked(True)
        self.radioButton.setAutoExclusive(True)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.horizontalLayout_3.addWidget(self.radioButton)
        self.radioButton_2 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.horizontalLayout_3.addWidget(self.radioButton_2)
        self.radioButton_3 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.horizontalLayout_3.addWidget(self.radioButton_3)
        self.radioButton_4 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.horizontalLayout_3.addWidget(self.radioButton_4)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_3, 5, 2, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.radioButton_7 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_7.setObjectName(_fromUtf8("radioButton_7"))
        self.horizontalLayout_4.addWidget(self.radioButton_7)
        self.radioButton_8 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_8.setChecked(True)
        self.radioButton_8.setObjectName(_fromUtf8("radioButton_8"))
        self.horizontalLayout_4.addWidget(self.radioButton_8)
        self.radioButton_9 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_9.setObjectName(_fromUtf8("radioButton_9"))
        self.horizontalLayout_4.addWidget(self.radioButton_9)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_4, 8, 2, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.spinBox_4 = QtGui.QSpinBox(self.gridLayoutWidget)
        self.spinBox_4.setProperty("value", 1)
        self.spinBox_4.setObjectName(_fromUtf8("spinBox_4"))
        self.horizontalLayout_5.addWidget(self.spinBox_4)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout_5, 9, 2, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(0, -1, 20, -1)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.label_12 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_6.addWidget(self.label_12)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.toolButton_2 = QtGui.QToolButton(self.gridLayoutWidget)
        self.toolButton_2.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.toolButton_2.setFont(font)
        self.toolButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolButton_2.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.toolButton_2.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        self.toolButton_2.setAutoRaise(True)
        self.toolButton_2.setArrowType(QtCore.Qt.NoArrow)
        self.toolButton_2.setObjectName(_fromUtf8("toolButton_2"))
        self.verticalLayout_3.addWidget(self.toolButton_2)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        self.gridLayout.addLayout(self.horizontalLayout_6, 9, 1, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, -1, 20, -1)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.label_16 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_7.addWidget(self.label_16)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.toolButton_3 = QtGui.QToolButton(self.gridLayoutWidget)
        self.toolButton_3.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.toolButton_3.setFont(font)
        self.toolButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolButton_3.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.toolButton_3.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        self.toolButton_3.setAutoRaise(True)
        self.toolButton_3.setArrowType(QtCore.Qt.NoArrow)
        self.toolButton_3.setObjectName(_fromUtf8("toolButton_3"))
        self.verticalLayout_4.addWidget(self.toolButton_3)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem7)
        self.horizontalLayout_7.addLayout(self.verticalLayout_4)
        self.gridLayout.addLayout(self.horizontalLayout_7, 8, 1, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, -1, 20, -1)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem8)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_9.addWidget(self.label_6)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.toolButton_5 = QtGui.QToolButton(self.gridLayoutWidget)
        self.toolButton_5.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.toolButton_5.setFont(font)
        self.toolButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolButton_5.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.toolButton_5.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        self.toolButton_5.setAutoRaise(True)
        self.toolButton_5.setArrowType(QtCore.Qt.NoArrow)
        self.toolButton_5.setObjectName(_fromUtf8("toolButton_5"))
        self.verticalLayout_6.addWidget(self.toolButton_5)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem9)
        self.horizontalLayout_9.addLayout(self.verticalLayout_6)
        self.gridLayout.addLayout(self.horizontalLayout_9, 7, 1, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(-1, -1, 20, -1)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem10)
        self.label_15 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_10.addWidget(self.label_15)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.toolButton_6 = QtGui.QToolButton(self.gridLayoutWidget)
        self.toolButton_6.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.toolButton_6.setFont(font)
        self.toolButton_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolButton_6.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.toolButton_6.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        self.toolButton_6.setAutoRaise(True)
        self.toolButton_6.setArrowType(QtCore.Qt.NoArrow)
        self.toolButton_6.setObjectName(_fromUtf8("toolButton_6"))
        self.verticalLayout_7.addWidget(self.toolButton_6)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem11)
        self.horizontalLayout_10.addLayout(self.verticalLayout_7)
        self.gridLayout.addLayout(self.horizontalLayout_10, 5, 1, 1, 1)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(-1, -1, 20, -1)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem12)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_11.addWidget(self.label_4)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.toolButton_8 = QtGui.QToolButton(self.gridLayoutWidget)
        self.toolButton_8.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.toolButton_8.setFont(font)
        self.toolButton_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolButton_8.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.toolButton_8.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        self.toolButton_8.setAutoRaise(True)
        self.toolButton_8.setArrowType(QtCore.Qt.NoArrow)
        self.toolButton_8.setObjectName(_fromUtf8("toolButton_8"))
        self.verticalLayout_9.addWidget(self.toolButton_8)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem13)
        self.horizontalLayout_11.addLayout(self.verticalLayout_9)
        self.gridLayout.addLayout(self.horizontalLayout_11, 4, 1, 1, 1)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(-1, -1, 20, -1)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem14)
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_12.addWidget(self.label)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.toolButton_10 = QtGui.QToolButton(self.gridLayoutWidget)
        self.toolButton_10.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.toolButton_10.setFont(font)
        self.toolButton_10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolButton_10.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.toolButton_10.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        self.toolButton_10.setAutoRaise(True)
        self.toolButton_10.setArrowType(QtCore.Qt.NoArrow)
        self.toolButton_10.setObjectName(_fromUtf8("toolButton_10"))
        self.verticalLayout_11.addWidget(self.toolButton_10)
        spacerItem15 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem15)
        self.horizontalLayout_12.addLayout(self.verticalLayout_11)
        self.gridLayout.addLayout(self.horizontalLayout_12, 3, 1, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.spinBox_1 = QtGui.QSpinBox(self.gridLayoutWidget)
        self.spinBox_1.setMaximum(4096)
        self.spinBox_1.setProperty("value", 300)
        self.spinBox_1.setObjectName(_fromUtf8("spinBox_1"))
        self.horizontalLayout_8.addWidget(self.spinBox_1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_8.addWidget(self.label_5)
        self.spinBox_2 = QtGui.QSpinBox(self.gridLayoutWidget)
        self.spinBox_2.setMaximum(4096)
        self.spinBox_2.setProperty("value", 300)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.horizontalLayout_8.addWidget(self.spinBox_2)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem16)
        self.gridLayout.addLayout(self.horizontalLayout_8, 4, 2, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lineEdit = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.buttonBox = QtGui.QDialogButtonBox(self.gridLayoutWidget)
        self.buttonBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Open)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout_2.addWidget(self.buttonBox, QtCore.Qt.AlignLeft)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem17)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.page)
        self.label_7.setGeometry(QtCore.QRect(220, 290, 112, 49))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.toolBox.addItem(self.page, _fromUtf8(""))
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 761, 307))
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.formLayoutWidget = QtGui.QWidget(self.page_2)
        self.formLayoutWidget.setGeometry(QtCore.QRect(-1, 19, 761, 181))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(-1, -1, 20, -1)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem18)
        self.label_8 = QtGui.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_13.addWidget(self.label_8)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.toolButton_11 = QtGui.QToolButton(self.formLayoutWidget)
        self.toolButton_11.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.toolButton_11.setFont(font)
        self.toolButton_11.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolButton_11.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.toolButton_11.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        self.toolButton_11.setAutoRaise(True)
        self.toolButton_11.setArrowType(QtCore.Qt.NoArrow)
        self.toolButton_11.setObjectName(_fromUtf8("toolButton_11"))
        self.verticalLayout_12.addWidget(self.toolButton_11)
        spacerItem19 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem19)
        self.horizontalLayout_13.addLayout(self.verticalLayout_12)
        self.formLayout.setLayout(1, QtGui.QFormLayout.LabelRole, self.horizontalLayout_13)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.spinBox_5 = QtGui.QSpinBox(self.formLayoutWidget)
        self.spinBox_5.setMaximum(360)
        self.spinBox_5.setObjectName(_fromUtf8("spinBox_5"))
        self.horizontalLayout_14.addWidget(self.spinBox_5)
        self.label_9 = QtGui.QLabel(self.formLayoutWidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_14.addWidget(self.label_9)
        self.spinBox_6 = QtGui.QSpinBox(self.formLayoutWidget)
        self.spinBox_6.setMaximum(360)
        self.spinBox_6.setObjectName(_fromUtf8("spinBox_6"))
        self.horizontalLayout_14.addWidget(self.spinBox_6)
        self.label_10 = QtGui.QLabel(self.formLayoutWidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_14.addWidget(self.label_10)
        self.spinBox_7 = QtGui.QSpinBox(self.formLayoutWidget)
        self.spinBox_7.setMaximum(360)
        self.spinBox_7.setObjectName(_fromUtf8("spinBox_7"))
        self.horizontalLayout_14.addWidget(self.spinBox_7)
        self.label_11 = QtGui.QLabel(self.formLayoutWidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_14.addWidget(self.label_11)
        spacerItem20 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem20)
        self.formLayout.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(-1, -1, 20, -1)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        spacerItem21 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem21)
        spacerItem22 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem22)
        self.label_13 = QtGui.QLabel(self.formLayoutWidget)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_15.addWidget(self.label_13)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.toolButton_13 = QtGui.QToolButton(self.formLayoutWidget)
        self.toolButton_13.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.toolButton_13.setFont(font)
        self.toolButton_13.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolButton_13.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.toolButton_13.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        self.toolButton_13.setAutoRaise(True)
        self.toolButton_13.setArrowType(QtCore.Qt.NoArrow)
        self.toolButton_13.setObjectName(_fromUtf8("toolButton_13"))
        self.verticalLayout_14.addWidget(self.toolButton_13)
        spacerItem23 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem23)
        self.horizontalLayout_15.addLayout(self.verticalLayout_14)
        self.formLayout.setLayout(2, QtGui.QFormLayout.LabelRole, self.horizontalLayout_15)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.spinBox_8 = QtGui.QSpinBox(self.formLayoutWidget)
        self.spinBox_8.setObjectName(_fromUtf8("spinBox_8"))
        self.horizontalLayout_16.addWidget(self.spinBox_8)
        spacerItem24 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem24)
        self.formLayout.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout_16)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setContentsMargins(-1, -1, 20, -1)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        spacerItem25 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem25)
        spacerItem26 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem26)
        self.label_14 = QtGui.QLabel(self.formLayoutWidget)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_17.addWidget(self.label_14)
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.toolButton_14 = QtGui.QToolButton(self.formLayoutWidget)
        self.toolButton_14.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.toolButton_14.setFont(font)
        self.toolButton_14.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolButton_14.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.toolButton_14.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        self.toolButton_14.setAutoRaise(True)
        self.toolButton_14.setArrowType(QtCore.Qt.NoArrow)
        self.toolButton_14.setObjectName(_fromUtf8("toolButton_14"))
        self.verticalLayout_15.addWidget(self.toolButton_14)
        spacerItem27 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem27)
        self.horizontalLayout_17.addLayout(self.verticalLayout_15)
        self.formLayout.setLayout(3, QtGui.QFormLayout.LabelRole, self.horizontalLayout_17)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.kcolorbutton = KColorButton(self.formLayoutWidget)
        self.kcolorbutton.setColor(QtGui.QColor(255, 255, 255))
        self.kcolorbutton.setDefaultColor(QtGui.QColor(255, 255, 255))
        self.kcolorbutton.setAlphaChannelEnabled(False)
        self.kcolorbutton.setObjectName(_fromUtf8("kcolorbutton"))
        self.horizontalLayout_18.addWidget(self.kcolorbutton)
        spacerItem28 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem28)
        self.formLayout.setLayout(3, QtGui.QFormLayout.FieldRole, self.horizontalLayout_18)
        spacerItem29 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout.setItem(4, QtGui.QFormLayout.LabelRole, spacerItem29)
        spacerItem30 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout.setItem(4, QtGui.QFormLayout.FieldRole, spacerItem30)
        self.toolBox.addItem(self.page_2, _fromUtf8(""))
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 410, 761, 102))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(20, -1, 20, -1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton_2 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout.addWidget(self.pushButton_2)
        spacerItem31 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem31)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem32 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem32)
        self.pushButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.verticalLayout.addWidget(self.pushButton)
        SudokuSolver.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(SudokuSolver)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 802, 30))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        SudokuSolver.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(SudokuSolver)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        SudokuSolver.setStatusBar(self.statusbar)
        self.actionOpen_database_directory = QtGui.QAction(SudokuSolver)
        self.actionOpen_database_directory.setObjectName(_fromUtf8("actionOpen_database_directory"))
        self.actionClose = QtGui.QAction(SudokuSolver)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionAbout = QtGui.QAction(SudokuSolver)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuFile.addAction(self.actionOpen_database_directory)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuAbout.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(SudokuSolver)
        self.toolBox.setCurrentIndex(0)

        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), self.open_std_directory)
        QtCore.QMetaObject.connectSlotsByName(SudokuSolver)

    def retranslateUi(self, SudokuSolver):
        SudokuSolver.setWindowTitle(_translate("SudokuSolver", "SudokuSolver", None))
        self.radioButton_6.setText(_translate("SudokuSolver", "no", None))
        self.radioButton_5.setText(_translate("SudokuSolver", "yes", None))
        self.radioButton.setText(_translate("SudokuSolver", "0", None))
        self.radioButton_2.setText(_translate("SudokuSolver", "1", None))
        self.radioButton_3.setText(_translate("SudokuSolver", "2", None))
        self.radioButton_4.setText(_translate("SudokuSolver", "3", None))
        self.radioButton_7.setText(_translate("SudokuSolver", "solved", None))
        self.radioButton_8.setText(_translate("SudokuSolver", "partially solved", None))
        self.radioButton_9.setText(_translate("SudokuSolver", "not solved", None))
        self.label_12.setText(_translate("SudokuSolver", "Number of images", None))
        self.toolButton_2.setText(_translate("SudokuSolver", "?", None))
        self.label_16.setText(_translate("SudokuSolver", "Completion stage  ", None))
        self.toolButton_3.setText(_translate("SudokuSolver", "?", None))
        self.label_6.setText(_translate("SudokuSolver", "Errors", None))
        self.toolButton_5.setText(_translate("SudokuSolver", "?", None))
        self.label_15.setText(_translate("SudokuSolver", "Difficulty  ", None))
        self.toolButton_6.setText(_translate("SudokuSolver", "?", None))
        self.label_4.setText(_translate("SudokuSolver", "Resolution", None))
        self.toolButton_8.setText(_translate("SudokuSolver", "?", None))
        self.toolButton_8.pressed.connect(self.info_popup_2)
        self.label.setText(_translate("SudokuSolver", "Path to the database", None))
        self.toolButton_10.setText(_translate("SudokuSolver", "?", None))
        self.toolButton_10.pressed.connect(self.info_popup_1)
        self.label_5.setText(_translate("SudokuSolver", "x", None))
        self.label_7.setText(_translate("SudokuSolver", "Completion stage  ", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("SudokuSolver", "Standard view", None))
        self.label_8.setText(_translate("SudokuSolver", "Camera position  ", None))
        self.toolButton_11.setText(_translate("SudokuSolver", "?", None))
        self.label_9.setText(_translate("SudokuSolver", "  X-axis  ", None))
        self.label_10.setText(_translate("SudokuSolver", "  Y-axis  ", None))
        self.label_11.setText(_translate("SudokuSolver", "  Z-axis  ", None))
        self.label_13.setText(_translate("SudokuSolver", "Lightning  ", None))
        self.toolButton_13.setText(_translate("SudokuSolver", "?", None))
        self.label_14.setText(_translate("SudokuSolver", "Background color  ", None))
        self.toolButton_14.setText(_translate("SudokuSolver", "?", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("SudokuSolver", "Expert view", None))
        self.pushButton_2.setText(_translate("SudokuSolver", "Show preview", None))
        self.pushButton.setText(_translate("SudokuSolver", "Generate", None))
        self.menuFile.setTitle(_translate("SudokuSolver", "File", None))
        self.menuAbout.setTitle(_translate("SudokuSolver", "About", None))
        self.actionOpen_database_directory.setText(_translate("SudokuSolver", "Open database directory", None))
        self.actionOpen_database_directory.triggered.connect(self.open_directory)
        self.actionClose.setText(_translate("SudokuSolver", "Quit", None))
        self.actionClose.triggered.connect(self.close_application)
        self.actionAbout.setText(_translate("SudokuSolver", "About", None))
        self.actionAbout.triggered.connect(self.about_popup)


    def open_std_directory(self):
        dname = QtGui.QFileDialog.getExistingDirectory()
        print dname
        self.lineEdit.setText(dname)

    def open_directory(self):
        dname = QtGui.QFileDialog.getExistingDirectory()
        print dname


    def close_application(self):
        sys.exit()

    def about_popup(self):
        ppa = QtGui.QWidget()
        result = QtGui.QMessageBox.information(ppa,'About','simulation tool version 0.3')


    def info_popup_1(self):
        ppa = QtGui.QWidget()
        result = QtGui.QMessageBox.information(ppa,'Information','Set standard path for the sudoku directory.')

    def info_popup_2(self):
        ppa = QtGui.QWidget()
        result = QtGui.QMessageBox.information(ppa,'Information','Set resolution of the generated pictures.')

    def info_popup_3(self):
        ppa = QtGui.QWidget()
        result = QtGui.QMessageBox.information(ppa,'Information','At the moment two tasks implemented \n simulations for SudokuSolver and SmartFridge.')

    def info_popup_4(self):
        ppa = QtGui.QWidget()
        result = QtGui.QMessageBox.information(ppa,'Information','At the moment two tasks implemented \n simulations for SudokuSolver and SmartFridge.')

    def info_popup_5(self):
        ppa = QtGui.QWidget()
        result = QtGui.QMessageBox.information(ppa,'Information','At the moment two tasks implemented \n simulations for SudokuSolver and SmartFridge.')


    def info_popup_6(self):
        ppa = QtGui.QWidget()
        result = QtGui.QMessageBox.information(ppa,'Information','At the moment two tasks implemented \n simulations for SudokuSolver and SmartFridge.')


    def info_popup_7(self):
        ppa = QtGui.QWidget()
        result = QtGui.QMessageBox.information(ppa,'Information','At the moment two tasks implemented \n simulations for SudokuSolver and SmartFridge.')


    def info_popup_8(self):
        ppa = QtGui.QWidget()
        result = QtGui.QMessageBox.information(ppa,'Information','At the moment two tasks implemented \n simulations for SudokuSolver and SmartFridge.')

    def info_popup_9(self):
        ppa = QtGui.QWidget()
        result = QtGui.QMessageBox.information(ppa,'Information','At the moment two tasks implemented \n simulations for SudokuSolver and SmartFridge.')




def main():
    import sys
    app = QtGui.QApplication(sys.argv)
    SudokuSolver = QtGui.QMainWindow()
    ui = Ui_SudokuSolver()
    ui.setupUi(SudokuSolver)
    SudokuSolver.show()
    sys.exit(app.exec_())


from PyKDE4.kdeui import KColorButton

if __name__ == "__main__":
    main()